### ISSUE TITLE
Tapable.plugin deprecation warnings

### ISSUE THREAD

**Issue by elderapo** [getsentry/sentry-webpack-plugin#116]
Using rewired create-react-app 2

```bash
(node:6144) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at SentryPlugin.apply (/src/app/node_modules/webpack-sentry-plugin/dist/index.js:100:16)
    at webpack (/src/app/node_modules/webpack/lib/webpack.js:47:13)
    at build (/src/app/node_modules/react-scripts/scripts/build.js:146:18)
    at checkBrowsers.then.then.previousFileSizes (/src/app/node_modules/react-scripts/scripts/build.js:86:12)
```

**Comment by kamilogorek** [comment]
Closing due to the issue getting out-dated. Feel free to ping me to reopen it if it's still relevant.
