### ISSUE TITLE
Using the plugin inside Heroku

### ISSUE THREAD

**Issue by Ancinek** [getsentry/sentry-webpack-plugin#118]
Hey, I have the plugin configured and it's working fine locally.
As soon as I push it to Heroku it stops working giving me the following error output:

```
Error: Command failed: /tmp/build_e3ae44a78c063d6493d3fdfc983bd8d6/client/node_modules/@sentry/cli/sentry-cli releases propose-version
  INFO    2019-04-16 13:33:13.141611957 +00:00 Loaded config from /tmp/build_e3ae44a78c063d6493d3fdfc983bd8d6/client/.sentryclirc
  DEBUG   2019-04-16 13:33:13.141666891 +00:00 sentry-cli version: 1.41.0, platform: "linux", architecture: "x86_64"
  INFO    2019-04-16 13:33:13.141684793 +00:00 sentry-cli was invoked with the following command line: "/tmp/build_e3ae44a78c063d6493d3fdfc983bd8d6/client/node_modules/@sentry/cli/sentry-cli" "releases" "propose-version"
  DEBUG   2019-04-16 13:33:13.141916192 +00:00 error: running update nagger
  DEBUG   2019-04-16 13:33:13.141939514 +00:00 skipping update nagger because session is not attended
error: Could not automatically determine release name
  DEBUG   2019-04-16 13:33:13.142576118 +00:00 client close; no transport to shut down  (from sentry)
    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

Any ideas what is wrong?

**Comment by greveritt** [comment]
I keep having the same problem, too. I'm using Webpack, which keeps generating an absolute path to `require` the module from. Best guess I could come up with is that passing a path to the JavaScript sources somehow forced Webpack to use an absolute path for this module, but I don't know the internals of Sentry or Webpack enough to really say; I may be way off base here.

**Comment by kamilogorek** [comment]
@Ancinek @greveritt can you give this a try:

```
heroku labs:enable runtime-dyno-metadata -a <app name>
```

**Comment by greveritt** [comment]
@kamilogorek Would that metadata allow it to skip requiring absolute paths during webpack build? If so, I suppose we'd have to enable the labs feature before the build runs. I would test this right now, but my review app is no longer using this webpack plugin; we decided to try another approach for now.

**Comment by greveritt** [comment]
@kamilogorek I have decided to try building a new branch that does use this plugin. I enabled the feature on Heroku even though it hasn't even started the actual build there yet. We'll see how this goes.

**Comment by greveritt** [comment]
@kamilogorek I'm still experiencing the same crash.

**Comment by greveritt** [comment]
@kamilogorek Would you like a build log from Heroku to help you debug this? My last log was very similar to the one @Ancinek put at the top of the thread.

**Comment by kamilogorek** [comment]
@greveritt according to the log, what's failing is our CLI and this plugin is just a wrapper around it, thus it cannot fix any underlying issues. Can you repost this issue here please - https://github.com/getsentry/sentry-cli

**Comment by greveritt** [comment]
Sorry @kamilogorek , but on closer inspection there is a big difference between my crash log and @Ancinek's: mine does have to do with the failure to find the webpack plugin, not the CLI. I created a new Heroku app with the failing code and attached a runtime log snippet below:

```
2019-05-16T14:04:34.147860+00:00 heroku[web.1]: Starting process with command `bundle exec nextjs-rails-server`
2019-05-16T14:04:38.426427+00:00 app[web.1]: Starting server on port 58604...
2019-05-16T14:04:38.435986+00:00 app[web.1]: proxy | started with pid 20
2019-05-16T14:04:38.436069+00:00 app[web.1]: frontend | started with pid 21
2019-05-16T14:04:38.436142+00:00 app[web.1]: backend | started with pid 23
2019-05-16T14:04:38.963319+00:00 app[web.1]: proxy | Waiting until 40926 is ready to receive requests…
2019-05-16T14:04:38.997918+00:00 app[web.1]: frontend | Waiting until 41306 is ready to receive requests…
2019-05-16T14:04:44.709066+00:00 app[web.1]: backend | => Booting Puma
2019-05-16T14:04:44.709229+00:00 app[web.1]: backend | => Rails 5.2.3 application starting in production
2019-05-16T14:04:44.709393+00:00 app[web.1]: backend | => Run `rails server -h` for more startup options
2019-05-16T14:04:44.709766+00:00 app[web.1]: backend | I, [2019-05-16T09:04:44.313371 #23]  INFO -- : Raven 2.9.0 ready to catch errors
2019-05-16T14:04:45.814400+00:00 app[web.1]: backend | Puma starting in single mode...
2019-05-16T14:04:45.814474+00:00 app[web.1]: backend | * Version 3.12.1 (ruby 2.5.3-p105), codename: Llamas in Pajamas
2019-05-16T14:04:45.814555+00:00 app[web.1]: backend | * Min threads: 20, max threads: 20
2019-05-16T14:04:45.814659+00:00 app[web.1]: backend | * Environment: production
2019-05-16T14:04:45.814788+00:00 app[web.1]: backend | * Listening on tcp://0.0.0.0:41306
2019-05-16T14:04:45.814883+00:00 app[web.1]: backend | Use Ctrl-C to stop
2019-05-16T14:04:46.084557+00:00 app[web.1]: backend | D, [2019-05-16T09:04:46.083825 #23] DEBUG -- : [d5ca1e2e-d955-4f8e-af49-0a714d10557c]    (2.0ms)            SELECT ff.key AS feature_key, fg.key, fg.value
2019-05-16T14:04:46.084651+00:00 app[web.1]: backend |           FROM flipper_features ff
2019-05-16T14:04:46.084776+00:00 app[web.1]: backend |           LEFT JOIN flipper_gates fg ON ff.key = fg.feature_key
2019-05-16T14:04:46.084884+00:00 app[web.1]: backend |
2019-05-16T14:04:46.119243+00:00 app[web.1]: backend | I, [2019-05-16T09:04:46.118684 #23]  INFO -- : [d5ca1e2e-d955-4f8e-af49-0a714d10557c] method=GET path=/ format=*/* controller=StatusController action=show status=200 duration=0.80 view=0.34 db=0.00
2019-05-16T14:04:46.130404+00:00 app[web.1]: frontend | Port 41306 is ready to receive requests!
2019-05-16T14:04:47.184344+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:47.886646+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:48.556561+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:48.748358+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:45+00:00 app[heroku-redis]: source=REDIS addon=redis-animate-28666 sample#active-connections=1 sample#load-avg-1m=0.225 sample#load-avg-5m=0.28 sample#load-avg-15m=0.25 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664288kB sample#memory-free=12622644kB sample#memory-cached=1030332kB sample#memory-redis=308864bytes sample#hit-rate=1 sample#evicted-keys=0
2019-05-16T14:04:45+00:00 app[heroku-redis]: source=REDIS_CACHE addon=redis-angular-41378 sample#active-connections=1 sample#load-avg-1m=0.225 sample#load-avg-5m=0.28 sample#load-avg-15m=0.25 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664288kB sample#memory-free=12622644kB sample#memory-cached=1030332kB sample#memory-redis=308864bytes sample#hit-rate=1 sample#evicted-keys=0
2019-05-16T14:04:49.198881+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.296665+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.455850+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.481967+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.539299+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.672178+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.747052+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:49.805353+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.126264+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.177095+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.309864+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.324099+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.440022+00:00 app[web.1]: frontend | [styled-jsx] Loading plugin from path: /app/node_modules/styled-jsx-plugin-postcss/index.js
2019-05-16T14:04:50.531305+00:00 app[web.1]: frontend | next.js is ready to take requests on port 40926
2019-05-16T14:04:51.113344+00:00 app[web.1]: frontend | { Error: Cannot find module '/tmp/build_ded2d13ce55e9b3b5341baf73b6447b8/node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js'
2019-05-16T14:04:51.113510+00:00 app[web.1]: frontend |     at Function.Module._resolveFilename (module.js:548:15)
2019-05-16T14:04:51.113618+00:00 app[web.1]: frontend |     at Function.wrappedResolveFilename [as _resolveFilename] (/app/node_modules/newrelic/lib/shimmer.js:367:39)
2019-05-16T14:04:51.113725+00:00 app[web.1]: frontend |     at Function.Module._load (module.js:475:25)
2019-05-16T14:04:51.113837+00:00 app[web.1]: frontend |     at Function.wrappedLoad (/app/node_modules/newrelic/lib/shimmer.js:373:38)
2019-05-16T14:04:51.113942+00:00 app[web.1]: frontend |     at Function.<anonymous> (/app/node_modules/@sentry/node/src/integrations/console.ts:37:43)
2019-05-16T14:04:51.114056+00:00 app[web.1]: frontend |     at Function._load (/app/node_modules/@sentry/node/src/integrations/http.ts:73:43)
2019-05-16T14:04:51.114168+00:00 app[web.1]: frontend |     at Module.require (module.js:597:17)
2019-05-16T14:04:51.114289+00:00 app[web.1]: frontend |     at require (internal/module.js:11:18)
2019-05-16T14:04:51.114401+00:00 app[web.1]: frontend |     at Object.85 (/app/app/interface/.next/server/static/uh53oWC8OxwSSTuOAzk23/pages/webpack:/external "/tmp/build_ded2d13ce55e9b3b5341baf73b6447b8/node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js":1:1)
2019-05-16T14:04:51.114515+00:00 app[web.1]: frontend |     at __webpack_require__ (/app/app/interface/.next/server/static/uh53oWC8OxwSSTuOAzk23/pages/webpack:/webpack/bootstrap:21:1) code: 'MODULE_NOT_FOUND' }
2019-05-16T14:05:34.625373+00:00 heroku[web.1]: State changed from starting to crashed
2019-05-16T14:05:34.518107+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-05-16T14:05:34.518239+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-05-16T14:05:34.609010+00:00 heroku[web.1]: Process exited with status 137
```

**Comment by greveritt** [comment]
@kamilogorek Do you still think I should make this an issue on the CLI repo? Or perhaps I should make a new issue on this repository since the error is happening outside of the CLI module for me?

**Comment by kamilogorek** [comment]
Original issue should be reported to cli repo, and followup issue has it's own page now, so closing this one.

**Comment by greveritt** [comment]
Thanks, @kamilogorek
