### ISSUE TITLE
error in upload source map in vue

### ISSUE THREAD

**Issue by sbqsbqsbq** [getsentry/sentry-webpack-plugin#176]
Hi, there. I'm trying to upload my source map, but it doesn't work properly.
the log is below.

```
ERROR  Failed to compile with 1 errors                                                                                                                                    5:48:05 PM

 error  in ./node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 3)
releasePromise.then is not a function
    at PoolWorker.fromErrorObj (/Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Socket.onChunk (/Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/thread-loader/dist/readBuffer.js:36:9)
    at Object.sentryLoader (/Users/juseonghyeok/Dev/github/mysterico/latte-builder/Latte-Client/node_modules/@sentry/webpack-plugin/src/sentry.loader.js:4:18)

 @ multi ./node_modules/@sentry/webpack-plugin/src/sentry-webpack.module.js ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't know how to resolve this. How can I upload my source map properly?

**Comment by kamilogorek** [comment]
What's your webpack config? Version? And other upload flow setup?

**Comment by sbqsbqsbq** [comment]
```
module.exports = {
  runtimeCompiler: true,

  configureWebpack: {
    optimization: {
      minimizer: isProd
        ? [
            new UglifyJsPlugin({
              sourceMap: true,
              uglifyOptions: {
                compress: {
                  // warnings: false,
                  drop_console: true,
                },
              },
            }),
          ]
        : [],
    },
    plugins: isProd
      ? [
          new WebpackAutoInject({
            PACKAGE_JSON_PATH: './package.json',
            PACKAGE_JSON_INDENT: 4,
            components: {
              AutoIncreaseVersion: true,
              InjectAsComment: true,
              InjectByTag: true,
            },
            componentsOptions: {
              AutoIncreaseVersion: {
                runInWatchMode: false, // it will increase version with every single build!
              },
              InjectAsComment: {
                tag: 'Version: {version} - {date}',
                dateFormat: 'h:MM:ss TT', // change timezone: `UTC:h:MM:ss` or `GMT:h:MM:ss`
                multiLineCommentType: false, // use `/** */` instead of `//` as comment block
              },
            },
          }),
        ]
      : [],
  },

  pluginOptions: {
    i18n: {
      locale: 'ko',
      fallbackLocale: 'ko',
      localeDir: 'locales',
      enableInSFC: true,
    },
  },

```

the above is a part of my webpack configuration file, and webpack version is `4.41.6`.

**Comment by kamilogorek** [comment]
I don't see any `SentryWebpackPlugin` reference in here 🤔

**Comment by sbqsbqsbq** [comment]
I've already applied the below code. However, it doesn't work well. In addition, the above error occurred.

```
  plugins: [
    new SentryWebpackPlugin({
      include: '.',
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties'
    })
  ]
```

**Comment by kamilogorek** [comment]
Unfortunately without providing a concrete repro-case which i can run locally it's very hard to tell what went wrong. It'd be great if you could provide something of that sort.

**Comment by kamilogorek** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Comment by fengyuanchen** [comment]
Just found a solution, set the [`parallel`](https://cli.vuejs.org/config/#parallel) option to `false` to disable the `thread-loader`:

```js
// vue.config.js
module.exports = {
  parallel: false,
  // ...
};
```
