### ISSUE TITLE
sentryCli.createRelease is not a function

### ISSUE THREAD

**Issue by EirikBirkeland** [getsentry/sentry-webpack-plugin#19]
Version: `@sentry/webpack-plugin@1.1.2`

Error:

``` bash
/workdir/node_modules/@sentry/webpack-plugin/src/index.js:34
      .createRelease(release)
       ^

TypeError: sentryCli.createRelease is not a function
    at Compiler.<anonymous> (/home/eb/Share/front/front.2407/node_modules/@sentry/webpack-plugin/src/index.js:34:8)
    at next (/home/eb/Share/front/front.2407/node_modules/tapable/lib/Tapable.js:220:14)
    at callback (/home/eb/Share/front/front.2407/node_modules/copy-webpack-plugin/dist/index.js:129:17)
    at Compiler.<anonymous> (/home/eb/Share/front/front.2407/node_modules/copy-webpack-plugin/dist/index.js:155:13)
    at Compiler.applyPluginsAsyncSeries1 (/home/eb/Share/front/front.2407/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/home/eb/Share/front/front.2407/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/home/eb/Share/front/front.2407/node_modules/webpack/lib/Compiler.js:350:15)
    at /home/eb/Share/front/front.2407/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/home/eb/Share/front/front.2407/node_modules/async/dist/async.js:1050:13)
    at /home/eb/Share/front/front.2407/node_modules/async/dist/async.js:958:16
    at /home/eb/Share/front/front.2407/node_modules/temp-write/node_modules/graceful-fs/graceful-fs.js:104:5
    at /home/eb/Share/front/front.2407/node_modules/gulp-cssmin/node_modules/graceful-fs/graceful-fs.js:104:5
    at /home/eb/Share/front/front.2407/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
```

Webpack config:

 ``` javascript
new SentryCliPlugin({
      release: function(hash) {
        return hash.slice(0, 5);
      },
      include: '.',
      ignoreFile: '.sentrycliignore',
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties'
    })
```

Lastly, my `.sentryclirc`:

```
[defaults]
project=projectname
org=myorgname
```

**Comment by EirikBirkeland** [comment]
And removing this part from the config avoids the error:

```
     release: function(hash) {
       return hash.slice(0, 5);
     },
```

**Comment by HazAT** [comment]
@EirikBirkeland We unpublished 1.28.0
This PR fixes the issue here: https://github.com/getsentry/sentry-webpack-plugin/pull/18
