### ISSUE TITLE
Usage of plugin with webpack 5 and vue-cli breaks build

### ISSUE THREAD

**Issue by dmitry-sirotenko** [getsentry/sentry-webpack-plugin#355]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
@sentry/webpack-plugin 1.18.6
@sentry/cli 1.72.2
@vue/cli-service 5.0.1 (with webpack 5.69.1)
vue 2.6.14
node 17.4.0

### Steps to Reproduce

1. Initialized plugin in configureWebpackSection
2. Added configuration (everything is correct)
3. Started build process (tried local and docker)
4. Got the error

Tried to disable all plugins one by one. Everything works correctly. But once you enable this plugin, it fails in the end of build process. 
Then tried to remove package-lock.json with node_modules and install all dependencies from scratch. No effect.
Also initialized new empty project with the same packages' versions. Same result.

### Expected Result

Build process finishes successfully.

### Actual Result

Error: Build failed with errors.
    at /Users/dmitry/Development/some-private-project/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /Users/dmitry/Development/some-private-project/node_modules/webpack/lib/webpack.js:148:8
    at /Users/dmitry/Development/some-private-project/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Cache.js:150:23)
    at /Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Compiler.js:1212:15
    at Hook.eval [as callAsync] (eval at create (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Compiler.js:1205:23)
    at /Users/dmitry/Development/some-private-project/node_modules/webpack/lib/webpack.js:147:16
    at finalCallback (/Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Compiler.js:441:32)
    at /Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Compiler.js:458:13
    at Hook.eval [as callAsync] (eval at create (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:35:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/dmitry/Development/some-private-project/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at onCompiled (/Users/dmitry/Development/some-private-project/node_modules/webpack/lib/Compiler.js:456:21)

**Comment by dmitry-sirotenko** [comment]
Nope, will try

**Comment by kamilogorek** [comment]
Can you provide a repro-case by any chance? I'm able to successfully upload vue artifacts using webpack-plugin.

**Comment by rangjq** [comment]
i got a problem
I have successfully uploaded the sourcemap. You can see the version, but artifacts is 
![1646287926390](https://user-images.githubusercontent.com/89401805/156507038-4c5bf9b3-77a6-4ef5-9c86-51522f4d0c51.jpg)
0

**Comment by kamilogorek** [comment]
Then you have not successfully uploaded them 😅 can you provide upload logs?
Also is this SaaS or on-premise instance?

**Comment by looooool11111** [comment]
thank you for your reply. I can upload successfully under SaaS, but I can't upload on the server I deploy. I wonder if the server has restrictions on the upload permission of sentry?
My sentry service based on docker
error logs:- warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for ~/dist/2820.fa84bf8fb9d045eaeac3.js.)
~/dist/2936.9bb6f22c0fb4a8b8bcfa.js (no sourcemap ref)
![AFAEE627-EFB0-4801-9FAE-83F52F813976](https://user-images.githubusercontent.com/89401805/156539035-e57d2859-3067-46cb-ae2e-d2d5566181ee.png)
![EFB0B129-6FD7-491A-9C53-CE4D88B9F544](https://user-images.githubusercontent.com/89401805/156539043-328e02a0-28be-46c7-8299-5fe7cd4e72a0.png)
![EFB0B129-6FD7-491A-9C53-CE4D88B9F544](https://user-images.githubusercontent.com/89401805/156539045-becee969-be43-4469-b69d-331b9bc2054b.png)

**Comment by looooool11111** [comment]
> > I can upload successfully under SaaS, but I can't upload on the server I deploy. I wonder if the server has restrictions on the upload permission of sentry?
> 
> That's misconfiguration on the server side. This is most likely caused by incorrectly mounting volume for filesystem storage - https://develop.sentry.dev/services/filestore/ ref: https://forum.sentry.io/t/offline-sourcemaps-not-used/548/3 There should be some other threads around similar issues on our forum as well.

Sorry for late response but I checked the dock configuration and found that it contains “sentry data”

What is the configuration of "File Storage"
I don't quite understand. 
Thank you very much for your reply
![35DCF9C1-0020-4CF2-8609-C575BB6D8D28](https://user-images.githubusercontent.com/89401805/156550102-375e3adc-07db-454d-b9ab-da245544daaa.png)

**Comment by kamilogorek** [comment]
You need to ask here https://github.com/getsentry/self-hosted about the configuration of the server. I don't have enough understanding to help you in this repo. The linked thread has also some insights, as well as this query - https://forum.sentry.io/search?q=sentry-data
