### ISSUE TITLE
Adding Sentry Plugin, Webpack stop to build

### ISSUE THREAD

**Issue by alessandro308** [getsentry/sentry-webpack-plugin#434]
### Environment

Node 14.19.2
"webpack": "^5.72.0",
"webpack-cli": "^3.3.11",
    "@sentry/browser": "^6.12.0",
    "@sentry/integrations": "^6.12.0",
    "@sentry/tracing": "^6.12.0",
    "@sentry/webpack-plugin": "^1.17.1",

### Steps to Reproduce

I just added:
```
 new SentryCliPlugin({
                    authToken: '<omitted>',
                    org: 'domotz',
                    project: 'app',
                    release: PACKAGE_VERSION,
                    include: [
                        'www',
                    ],
                    ignoreFile: '.gitignore',
                    ignore: [
                        'node_modules',
                        'webpack.config.js',
                    ],
                    configFile: 'sentry.properties',
                    urlPrefix: argv.sentryNoUrlPrefix ? null : '~/webapp',
                }),
 ```

### Actual Result

```
/Users/alessandro/domotz/mobile_app/ionicApp/node_modules/@sentry/webpack-plugin/src/index.js:133
            throw e;
            ^

Error: No code generation entry for /Users/alessandro/mobile_app/ionicApp/node_modules/webpack-strip-block/index.js!/Users/alessandro/mobile_app/ionicApp/src/loadTranslations.js (existing entries: /Users/alessandro/mobile_app/ionicApp/node_m ....

 at CodeGenerationResults.get (/Users/alessandro/domotz/mobile_app/ionicApp/node_modules/webpack/lib/CodeGenerationResults.js:37:10)
    at /Users/alessandro/mobile_app/ionicApp/node_modules/@sentry/webpack-plugin/src/index.js:109:65
    at Set.forEach (<anonymous>)
    at /Users/alessandro/mobile_app/ionicApp/node_modules/@sentry/webpack-plugin/src/index.js:103:29
    at Hook.eval [as call] (eval at create (/Users/alessandro/mobile_app/ionicApp/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/alessandro/mobile_app/ionicApp/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at /Users/alessandro/mobile_app/ionicApp/node_modules/webpack/lib/Compilation.js:3022:38
    at /Users/alessandro/mobile_app/ionicApp/node_modules/webpack/lib/Compilation.js:3280:6
    at /Users/alessandro/mobile_app/ionicApp/node_modules/neo-async/async.js:2818:7
    at done (/Users/alessandro/mobile_app/ionicApp/node_modules/neo-async/async.js:3522:9)
    at /Users/alessandro/mobile_app/ionicApp/node_modules/webpack/lib/Compilation.js:3243:8
    at /Users/alessandro/mobile_app/ionicApp/node_modules/webpack/lib/Compilation.js:3352:32
    at /Users/alessandro/mobile_app/ionicApp/node_modules/webpack/lib/HookWebpackError.js:68:3
```

Even removing all the other loaders the error remains. Removing Sentry plugin the build succeed.

This catch (added by me) is able to catch the error in case, so the error is somewhere there:
file: @sentry/webpack-plugin/src/index.js
```
            const sourceMap = compilation.codeGenerationResults.get(module)
                .sources;


              const rawSource = sourceMap.get('javascript');

              if (rawSource) {
                sourceMap.set(
                  'javascript',
                  new RawSource(
                    `${rawSource.source()}
      (function (){
      var globalThis = (typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : typeof self !== 'undefined' ? self : {});
      globalThis.SENTRY_RELEASES = globalThis.SENTRY_RELEASES || {};
      globalThis.SENTRY_RELEASES["${options.project}@${
                      options.org
                    }"] = {"id":"${version}"};
      })();`
                  )
                );
              }
          }catch(e){
            console.log(e.toString().slice(0, 100));
            console.log(module.resource);
            throw e;
          }
          ```

**Comment by lforst** [comment]
Hey, can you try the newest version of the plugin (`2.0.0`) with the updated setup docs? https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/

I belive this might be fixed already.
